version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY={$JWT_REFRESH_SECRET_KEY}
    ports:
      - "89:89"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass  # Set the superuser password here
      POSTGRES_DB: ncaa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: